### ISSUE TITLE
how do I install this into a modern Android Studio project?

### ISSUE THREAD

**Issue by l0c0luke** [xxxajk/PhysicaloidLibrary#12]
i am struggling to figure this out. Sorry for noob question. Is it still as the Readme describes?

**Comment by xxxajk** [comment]
Short answer: Yes. :-)

**Comment by l0c0luke** [comment]
thank you for the patient answer, i got this figured out, and thank you for the continued work on this library. such a good feature with the remote update.

**Comment by xxxajk** [comment]
Did you know that it can also work over WiFi? That means esp8266 OTA too!
