### ISSUE TITLE
in stk500 step, i send 0x30 0x20, can not ricevo 0x14 0x10?

### ISSUE THREAD

**Issue by yangmin1234** [xxxajk/PhysicaloidLibrary#18]
in stk500 step, when i getsync send 0x30 0x20, cannot ricevo nothing?

**Comment by xxxajk** [comment]
I don't understand the question.

**Comment by yangmin1234** [comment]
Kiam mi realigas restarigon, mi sendas reset-ordonon 0x30 0x20 al Arduino. La aparato povas ricevi la komandon sed ne revenas.

**Comment by yangmin1234** [comment]
When I perform the reset, I want arduino to send a reset command 0x30 0x20, the device does not return any, is there some problem with my configuration?

**Comment by xxxajk** [comment]
resets are done using RTS and DTR.

**Comment by yangmin1234** [comment]
thank you, there is a problem with my configuration.
