### ISSUE TITLE
is the project alive?

### ISSUE THREAD

**Issue by voltangle** [xxxajk/PhysicaloidLibrary#20]
As in the title

**Comment by xxxajk** [comment]
yes... at least I'm actively using it....

**Comment by voltangle** [comment]
Why I actually asked: last commit was in 2018. It is like two years past from last commit. So I thought that project is dead. But I am happy to see that this Is not the case)

**Comment by xxxajk** [comment]
The original project that I forked from is long since dead, which is unfortunate.
I've just been extremely busy.
