### ISSUE TITLE
Remove need for closed source FTDI jar file

### ISSUE THREAD

**Issue by xxxajk** [xxxajk/PhysicaloidLibrary#3]
I have the knowledge on how to do this, and I plan on not having to depend on FTDI's cruft.
In short, I will be removing the need for the D2XX.jar file.

**Comment by DRSDavidSoft** [comment]
I think I now know how you plan on doing this, using [ftdi_sio.c](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/ftdi_sio.c), right? 😄 
Go for it, applaud for removing closed-source libraries!

**Comment by xxxajk** [comment]
Partially, I also work on this: https://github.com/felis/UHS30 which is going to get WCH support soon.

**Comment by xxxajk** [comment]
@DRSDavidSoft Will be working on this today. Will you be able to test?

**Comment by DRSDavidSoft** [comment]
@xxxajk Yes, gladly! I need to find my FTDI adapter first.

**Comment by xxxajk** [comment]
@DRSDavidSoft 
Initial testing shows 'works for me'. Give it a try. 

I'll be filling in the remaining missing features for CDC-ACM later today as well, namely the data size, parity and stop bits. These were never implemented even in the original library, and I know how to do it.

**Comment by xxxajk** [comment]
@DRSDavidSoft uploading works, updated test app.
Give a try please.

**Comment by DRSDavidSoft** [comment]
@xxxajk Sorry for the delay, IRL stuff. I'll run my own tests today and update with you soon.

**Comment by xxxajk** [comment]
All working, etc, yadda yadda, closing it.
