### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by fire1** [xxxajk/PhysicaloidLibrary#7]
From several days i'm trying to connect to several serial devices but without a result.
I Added PhysicaloidTest to my project and this is the output from debug:

> D/UsbCdcConnection: Cannot find VID:1027, PID:0
>                     Cannot find VID:3368, PID:0
>                     Cannot find VID:3368, PID:0
>                     Cannot find VID:4951, PID:0
>                     Cannot find VID:5538, PID:0
>                     Cannot find VID:4292, PID:0

Deppendency lib are added: physicaloidlibrary.jar && d2xx.jar

**Comment by xxxajk** [comment]
1: What devices are you attempting to connect exactly?
2: Are you using Linux or Windows for development?

**Comment by fire1** [comment]
On widows 10 is compiled...

Mega with CH**  and other with ftdi clone
Also Uno with ftdi clone and original ftdi UART to USB 
None of them works

**Comment by xxxajk** [comment]
Have you tried a different phone or tablet? If not, try, and see if that will work.
Some phones don't allow host mode, and some phones and tablets can have bugs. You may just be one of the unlucky people to have such a device.

**Comment by fire1** [comment]
Adding library folder  to the project fix this issue!
