### ISSUE TITLE
Broken serial baud rate

### ISSUE THREAD

**Issue by fire1** [xxxajk/PhysicaloidLibrary#8]
I'm struggling to get serial read to work... only output I'm having is:

>   Stream: ����������������������� 

Changing baud rate with method "setBaudrate()" did not help  (same baud rate for arduino and device 115200 && 9600 tested) 
also 

> new String(readBuffer, "UTF-8");  

did not fix it 

Is there some other way to fix it or debug it ?
It seems to be some problem with  baud rate...

**Comment by fire1** [comment]
Changing baud rate in 

> PhysicaloidLibrary\src\com\physicaloid\lib\usb\driver\uart\UartConfig.java

Fixes the communication 
Changing from `setConfig` or `setBaudrate` didn't change it ...

**Comment by hamidsani** [comment]
Make sure to call the setBaudrate method AFTER port is opened. If you look closer at setBaudrate method you'll find that when port is null (or it doesn't exist) then it just returns false.

**Comment by xxxajk** [comment]
Correct. All failed calls return false. You should always check the return values.

**Comment by fire1** [comment]
thanks!
